# .gitlab-ci for www-joshbeard.me
#
# 1. Build
# 2. Minify
# 3. Deploy to S3
#
# Variables set in GitLab vars:
# AWS_ACCESS_KEY_ID
# AWS_DEFAULT_REGION
# AWS_SECRET_ACCESS_KEY
# S3_BUCKET_NAME
#
---
stages:
  - build
  - minify
  - deploy

build:
  stage: build
  image:
    name: jekyll/jekyll
    entrypoint: ['']
  script:
    - jekyll build --config /site/._config.yml
  artifacts:
    paths:
      - _site
  only:
    - master

minify:
  stage: minify
  image:
    name: thekevjames/minify:2.5.2
    entrypoint: ['']
  dependencies:
    - build
  script: minify --recursive --output _site _site
  artifacts:
    paths:
      - _site
  only:
    - master

deploy:
  stage: deploy
  image:
    name: banst/awscli
    entrypoint: ['']
  dependencies:
    - minify
  script:
    - aws s3 sync _site/
      s3://$S3_BUCKET_NAME
      --delete
      --exclude ".git/*"
      --exclude ".gitlab-ci.yml"
      --exclude "README.md"
      --exclude "resume/*"
      --acl public-read
  only:
    - master
