# .gitlab-ci for www-joshbeard.me
#
# 1. Validate HTML
# 2. Minify
# 3. Deploy to S3
#
# Variables set in GitLab vars:
# AWS_ACCESS_KEY_ID
# AWS_DEFAULT_REGION
# AWS_SECRET_ACCESS_KEY
# S3_BUCKET_NAME
#
---
stages:
  - validate
  - minify
  - deploy

# Not validating css due to use of the 'calc()' function.
# Reference: https://www.w3.org/Bugs/Public/show_bug.cgi?id=18913
validation:
  stage: validate
  image:
    name: validator/validator
    entrypoint: ['']
  script:
    - vnu --also-check-css $CI_PROJECT_DIR/*.html

minify:
  stage: minify
  image:
    name: thekevjames/minify:2.5.2
    entrypoint: ['']
  script: minify --recursive --output $CI_PROJECT_DIR $CI_PROJECT_DIR
  artifacts:
    paths:
      - $CI_PROJECT_DIR
  only:
    - master

deploy:
  stage: deploy
  image:
    name: banst/awscli
    entrypoint: ['']
  dependencies:
    - minify
  script:
    - aws s3 sync .
      s3://$S3_BUCKET_NAME
      --delete
      --exclude ".git/*"
      --exclude ".gitlab-ci.yml"
      --exclude "README.md"
      --exclude "resume/*"
      --acl public-read
  only:
    - master
